const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Malibu",
    country: "United States"
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "New York City",
    country: "United States"
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 1000,
    location: "Aspen",
    country: "United States"
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Florence",
    country: "Italy"
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=60",
    price: 800,
    location: "Portland",
    country: "United States"
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Cancun",
    country: "Mexico"
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 900,
    location: "Lake Tahoe",
    country: "United States"
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Los Angeles",
    country: "United States"
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: "https://images.unsplash.com/photo-1519817650390-64a93db511ed?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Verbier",
    country: "Switzerland"
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania"
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands"
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 10000,
    location: "Fiji",
    country: "Fiji"
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Cotswolds",
    country: "United Kingdom"
  },
  {
    title: "Beachfront Retreat in Hawaii",
    description: "Relax on the pristine beaches of Hawaii in this luxurious beachfront retreat with stunning ocean views.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Maui",
    country: "United States",
  },
  {
    title: "Scenic Lakeside Cabin in Switzerland",
    description: "Enjoy breathtaking views of the Swiss Alps from this charming lakeside cabin, perfect for a peaceful getaway.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Lucerne",
    country: "Switzerland",
  },
  {
    title: "Oceanfront Villa in the Bahamas",
    description: "Escape to paradise in this luxurious oceanfront villa in the Bahamas. Enjoy private beach access and stunning sunsets.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Nassau",
    country: "Bahamas",
  },
  {
    title: "Riverside Cabin in New Zealand",
    description: "Experience the tranquility of New Zealand's wilderness in this cozy riverside cabin surrounded by native forests.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "Queenstown",
    country: "New Zealand",
  },
  {
    title: "Historic Riad in Marrakech",
    description: "Immerse yourself in Moroccan culture in this beautifully restored historic riad in the heart of Marrakech.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Marrakech",
    country: "Morocco",
  },
  {
    title: "Lakeside Villa in Italy",
    description: "Live la dolce vita in this elegant lakeside villa in Italy. Enjoy stunning lake views and Italian hospitality.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Lake Como",
    country: "Italy",
  },
  {
    title: "Private Island in the Philippines",
    description: "Escape to your own private island in the Philippines, surrounded by crystal-clear waters and pristine beaches.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 5000,
    location: "Palawan",
    country: "Philippines",
  },
  {
    title: "Countryside Cottage in France",
    description: "Experience French countryside charm in this quaint cottage surrounded by vineyards and rolling hills.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1400,
    location: "Burgundy",
    country: "France",
  },
  {
    title: "Urban Loft in Berlin",
    description: "Stay in style in this modern urban loft in the vibrant city of Berlin, known for its art and nightlife.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Sunny Villa in Santorini",
    description: "Enjoy breathtaking sunsets from this beautiful villa perched on the cliffs of Santorini, overlooking the Aegean Sea.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Mountain Lodge in Colorado",
    description: "Escape to the Rocky Mountains in this cozy mountain lodge with panoramic views of Colorado's natural beauty.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 1600,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Tropical Villa in Bali",
    description: "Indulge in luxury at this tropical villa in Bali, featuring private pools, lush gardens, and Balinese hospitality.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Secluded Cabin in Norway",
    description: "Find peace in this secluded cabin in Norway, nestled among fjords and forests with stunning natural views.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Bergen",
    country: "Norway",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the heart of the desert at this oasis in Dubai, featuring modern amenities and Arabian hospitality.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Dubai",
    country: "United Arab Emirates",
  },
  {
    title: "Rainforest Retreat in Costa Rica",
    description: "Immerse yourself in nature at this rainforest retreat in Costa Rica, surrounded by exotic wildlife and lush greenery.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 2300,
    location: "Monteverde",
    country: "Costa Rica",
  },
  {
    title: "Historic Mansion in Spain",
    description: "Stay in this historic mansion in Spain, offering elegant interiors and a glimpse into the country's rich heritage.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 2700,
    location: "Seville",
    country: "Spain",
  },
  {
    title: "Luxury Apartment in Tokyo",
    description: "Experience the vibrant city life in Tokyo from this luxury apartment, featuring modern design and top-notch amenities.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Cozy Cottage in Canada",
    description: "Enjoy a serene escape in this cozy cottage in Canada, surrounded by nature and perfect for a relaxing getaway.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Banff",
    country: "Canada",
  },
  {
    title: "Charming Bungalow in Thailand",
    description: "Stay in this charming bungalow in Thailand, offering a unique blend of traditional Thai architecture and modern comforts.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1900,
    location: "Chiang Mai",
    country: "Thailand",
  },
  {
    title: "Mountain Cabin in Austria",
    description: "Experience the Austrian Alps from this cozy mountain cabin, perfect for skiing and outdoor adventures.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 2100,
    location: "Innsbruck",
    country: "Austria",
  },
  {
    title: "Seaside Villa in Portugal",
    description: "Relax in this seaside villa in Portugal, offering stunning views of the Atlantic Ocean and luxurious amenities.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 2600,
    location: "Algarve",
    country: "Portugal",
  },
  {
    title: "Rustic Lodge in Montana",
    description: "Experience the rugged beauty of Montana in this rustic lodge, surrounded by mountains and wide-open spaces.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Bozeman",
    country: "United States",
  },
  {
    title: "Eco Lodge in South Africa",
    description: "Stay at this eco-friendly lodge in South Africa, offering luxury accommodations and stunning views of the African savannah.",
    image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=800&q=60",
    price: 3100,
    location: "Kruger National Park",
    country: "South Africa",
  },
  {
    title: "Urban Jungle Hostel",
    description: "A vibrant hostel in the heart of the city, perfect for backpackers and digital nomads.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=60",
    price: 700,
    location: "Bangkok",
    country: "Thailand"
  },
  {
    title: "Desert Dome Experience",
    description: "Sleep under the stars in a luxury desert dome with all modern amenities.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Jaisalmer",
    country: "India"
  },
  {
    title: "City Center Hotel Room",
    description: "A modern hotel room in the heart of the city, perfect for business and leisure travelers.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Delhi",
    country: "India"
  },
  {
    title: "Boutique Hostel Bed",
    description: "A cozy hostel bed in a stylish boutique hostel, great for solo travelers.",
    image: "https://images.unsplash.com/photo-1519974719765-e6559eac2575?auto=format&fit=crop&w=800&q=60",
    price: 600,
    location: "Barcelona",
    country: "Spain"
  },
  {
    title: "Luxury Resort Suite",
    description: "Spacious suite in a luxury resort with pool and sea view.",
    image: "https://images.unsplash.com/photo-1501117716987-c8e1ecb210fa?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Goa",
    country: "India"
  }
];

module.exports = { data: sampleListings };