let sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Malibu",
    country: "United States"
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "New York City",
    country: "United States"
    title: "National Museum",
    description: "The National Museum holds artifacts from prehistoric times to modern art. The museum covers over 5,000 years of Indian culture and history.",
    history: "Established in 1949, the museum was inaugurated on 15 August 1949. It was originally part of the Rashtrapati Bhavan.",
    relatedinfo: "The museum has over 200,000 works of art and regularly hosts special exhibitions.",
    image: "https://images.unsplash.com/photo-1514905552197-0610a4d8fd73?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Janpath, New Delhi, Delhi 110011, India",
    openingtime: "10:00 AM",
    closingtime: "6:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.5/5"
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 1000,
    location: "Aspen",
    country: "United States"
    title: "Indian Museum",
    description: "The Indian Museum in Kolkata is the largest and oldest museum in India, boasting a rich collection of antiques, armor, fossils, and paintings.",
    history: "Founded in 1814 by the Asiatic Society of Bengal, it is one of the earliest and most comprehensive museums in Asia.",
    relatedinfo: "It has six sections dedicated to Art, Archaeology, Anthropology, Geology, Zoology, and Economic Botany.",
    image: "https://www.bing.com/th/id/OIP.sdt4mo8qrRAl71XLSOv8pwHaE7?w=246&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "27, Jawaharlal Nehru Road, Park Street area, Kolkata, West Bengal 700016, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "50 rs.",
    ratings: "4.6/5"
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Florence",
    country: "Italy"
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=60",
    price: 800,
    location: "Portland",
    country: "United States"
    title: "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya",
    description: "This museum in Mumbai is a landmark heritage structure that displays artifacts from ancient Indian history, art, and culture.",
    history: "Established in 1922, it was formerly known as the Prince of Wales Museum of Western India and was renamed in honor of Maratha ruler Shivaji.",
    relatedinfo: "It houses over 50,000 artifacts including sculptures, manuscripts, and decorative arts.",
    image: "https://th.bing.com/th/id/OIP.Cwwi_ZAP-M8nQZn8El5lcgHaE8?w=276&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "159-161, Mahatma Gandhi Road, Kala Ghoda, Fort, Mumbai, Maharashtra 400032, India",
    openingtime: "10:15 AM",
    closingtime: "6:00 PM",
    ticketfees: "85 rs.",
    ratings: "4.5/5"
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Cancun",
    country: "Mexico"
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 900,
    location: "Lake Tahoe",
    country: "United States"
    title: "Salar Jung Museum",
    description: "The Salar Jung Museum in Hyderabad is one of the three National Museums of India, featuring an impressive collection of sculptures, paintings, textiles, and more.",
    history: "Inaugurated in 1951, the museum was founded by Nawab Mir Yousuf Ali Khan, Salar Jung III, who devoted his life to collecting these artifacts.",
    relatedinfo: "The museum is known for its collection of over 43,000 art objects and 50,000 books and manuscripts.",
    image: "https://th.bing.com/th?id=OIF.aR1NJON%2bbHRne3VeZ%2b1aaQ&w=192&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    location: "Darulshifa, Hyderabad, Telangana 500002, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.7/5"
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Los Angeles",
    country: "United States"
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: "https://images.unsplash.com/photo-1519817650390-64a93db511ed?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Verbier",
    country: "Switzerland"
    title: "Victoria Memorial",
    description: "The Victoria Memorial in Kolkata is a large marble building dedicated to the memory of Queen Victoria, with galleries showcasing British imperial history in India.",
    history: "Opened to the public in 1921, the building was designed by Sir William Emerson in a style blending British and Mughal elements.",
    relatedinfo: "The museum within the memorial houses 25 galleries, including the Royal Gallery, the National Leaders Gallery, and the Calcutta Gallery.",
    image: "https://th.bing.com/th/id/OIP.Q52QzZphWHXb9NoAAg7VFwHaE8?w=252&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "1, Queens Way, Kolkata, West Bengal 700071, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "30 rs.",
    ratings: "4.6/5"
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania"
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands"
    title: "Nehru Museum & Planetarium",
    description: "Located in New Delhi, the Nehru Museum & Planetarium, also known as the Nehru Memorial Museum and Library, is dedicated to India's first Prime Minister, Jawaharlal Nehru.",
    history: "Inaugurated in 1964, the museum was established to honor Nehru's contributions to Indian politics and education.",
    relatedinfo: "The museum features a variety of exhibits related to Nehru's life and India's post-independence history. The planetarium offers educational shows about space and astronomy.",
    image: "https://th.bing.com/th/id/OIP.WZjwYdYyYfAjVxGYfgetdAHaFD?w=239&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Teen Murti Bhavan, New Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "30 rs.",
    ratings: "4.4/5"
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 10000,
    location: "Fiji",
    country: "Fiji"
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Cotswolds",
    country: "United Kingdom"
    title: "Rajasthan State Museum",
    description: "Located in Jaipur, the Rajasthan State Museum features an impressive collection of artifacts showcasing the rich history and culture of Rajasthan.",
    history: "Founded in 1949, the museum is situated in the Albert Hall, a historic building that was established to house the museum's collection.",
    relatedinfo: "The museum’s exhibits include paintings, sculptures, textiles, and artifacts from various periods of Rajasthan's history.",
    image: "https://th.bing.com/th/id/OIP.9o1ptG6kiVfgUEbCv1OgCAHaE8?w=240&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3",
    location: "Albert Hall Museum, Ram Niwas Garden, Jaipur, Rajasthan 302004, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "50 rs.",
    ratings: "4.3/5"
  },
  {
    title: "Beachfront Retreat in Hawaii",
    description: "Relax on the pristine beaches of Hawaii in this luxurious beachfront retreat with stunning ocean views.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Maui",
    country: "United States",
  {
    title: "Delhi Museum",
    description: "The Delhi Museum, also known as the Delhi Archaeological Museum, displays a variety of artifacts from ancient Indian civilizations.",
    history: "Established in 1960, the museum focuses on the history and archaeology of Delhi and the surrounding regions.",
    relatedinfo: "Exhibits include ancient coins, pottery, and sculptures from the Mauryan, Gupta, and Mughal periods.",
    image: "https://th.bing.com/th/id/OIP.CnWk_Tdvl5fYJs5GhyxLKQHaE7?w=270&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Central Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.2/5"
  },
  {
    title: "Scenic Lakeside Cabin in Switzerland",
    description: "Enjoy breathtaking views of the Swiss Alps from this charming lakeside cabin, perfect for a peaceful getaway.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Lucerne",
    country: "Switzerland",
    title: "The National Gallery of Modern Art",
    description: "The National Gallery of Modern Art in New Delhi houses an extensive collection of modern and contemporary Indian art.",
    history: "Founded in 1954, the gallery is located in the former residence of the Maharaja of Jaipur.",
    relatedinfo: "The gallery features works by prominent Indian artists from the 19th century to the present day, including paintings, sculptures, and installations.",
    image: "https://th.bing.com/th/id/OIP.goRdFok4b1fBT-euzPDcUQHaEK?w=289&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Rajpath, Central Secretariat, New Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.5/5"
  },
  {
    title: "Oceanfront Villa in the Bahamas",
    description: "Escape to paradise in this luxurious oceanfront villa in the Bahamas. Enjoy private beach access and stunning sunsets.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Nassau",
    country: "Bahamas",
  },
  {
    title: "Riverside Cabin in New Zealand",
    description: "Experience the tranquility of New Zealand's wilderness in this cozy riverside cabin surrounded by native forests.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "Queenstown",
    country: "New Zealand",
    title: "The Asiatic Society",
    description: "The Asiatic Society Museum in Kolkata is renowned for its extensive collection of manuscripts, rare books, and historical artifacts related to Asia.",
    history: "Established in 1784 by Sir William Jones, the museum is one of the oldest institutions dedicated to the study of Asian culture and history.",
    relatedinfo: "The museum's collection includes over 100,000 manuscripts, including several ancient and rare texts.",
    image: "https://th.bing.com/th/id/OIP.FqY7NP6TKLvpq0XtdunCoAHaE7?w=290&h=193&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "1 Park Street, Kolkata, West Bengal 700016, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "Free",
    ratings: "4.4/5"
  },
  {
    title: "Historic Riad in Marrakech",
    description: "Immerse yourself in Moroccan culture in this beautifully restored historic riad in the heart of Marrakech.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Marrakech",
    country: "Morocco",
  },
  {
    title: "Lakeside Villa in Italy",
    description: "Live la dolce vita in this elegant lakeside villa in Italy. Enjoy stunning lake views and Italian hospitality.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Lake Como",
    country: "Italy",
    title: "Rajasthan State Museum",
    description: "Located in Jaipur, the Rajasthan State Museum features an impressive collection of artifacts showcasing the rich history and culture of Rajasthan.",
    history: "Founded in 1949, the museum is situated in the Albert Hall, a historic building that was established to house the museum's collection.",
    relatedinfo: "The museum’s exhibits include paintings, sculptures, textiles, and artifacts from various periods of Rajasthan's history.",
    image: "https://th.bing.com/th/id/OIP.CYUneaDCPTs9N1AaTyXu4QHaE8?w=248&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Albert Hall Museum, Ram Niwas Garden, Jaipur, Rajasthan 302004, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "50 rs.",
    ratings: "4.3/5"
  },
  {
    title: "Private Island in the Philippines",
    description: "Escape to your own private island in the Philippines, surrounded by crystal-clear waters and pristine beaches.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 5000,
    location: "Palawan",
    country: "Philippines",
    title: "Delhi Museum",
    description: "The Delhi Museum, also known as the Delhi Archaeological Museum, displays a variety of artifacts from ancient Indian civilizations.",
    history: "Established in 1960, the museum focuses on the history and archaeology of Delhi and the surrounding regions.",
    relatedinfo: "Exhibits include ancient coins, pottery, and sculptures from the Mauryan, Gupta, and Mughal periods.",
    image: "https://th.bing.com/th/id/OIP.hiMEX6HmSU79Y8mnPyw9fAHaFa?w=201&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Central Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.2/5"
  },
  {
    title: "Countryside Cottage in France",
    description: "Experience French countryside charm in this quaint cottage surrounded by vineyards and rolling hills.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1400,
    location: "Burgundy",
    country: "France",
  },
  {
    title: "Urban Loft in Berlin",
    description: "Stay in style in this modern urban loft in the vibrant city of Berlin, known for its art and nightlife.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Berlin",
    country: "Germany",
    title: "The National Gallery of Modern Art",
    description: "The National Gallery of Modern Art in New Delhi houses an extensive collection of modern and contemporary Indian art.",
    history: "Founded in 1954, the gallery is located in the former residence of the Maharaja of Jaipur.",
    relatedinfo: "The gallery features works by prominent Indian artists from the 19th century to the present day, including paintings, sculptures, and installations.",
    image: "https://th.bing.com/th/id/OIP.l_Iye0M95DUKoNhbHPg6tgHaEK?w=283&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Rajpath, Central Secretariat, New Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.5/5"
  },
  {
    title: "Sunny Villa in Santorini",
    description: "Enjoy breathtaking sunsets from this beautiful villa perched on the cliffs of Santorini, overlooking the Aegean Sea.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Mountain Lodge in Colorado",
    description: "Escape to the Rocky Mountains in this cozy mountain lodge with panoramic views of Colorado's natural beauty.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 1600,
    location: "Aspen",
    country: "United States",
    title: "Nehru Museum & Planetarium",
    description: "Located in New Delhi, the Nehru Museum & Planetarium, also known as the Nehru Memorial Museum and Library, is dedicated to India's first Prime Minister, Jawaharlal Nehru.",
    history: "Inaugurated in 1964, the museum was established to honor Nehru's contributions to Indian politics and education.",
    relatedinfo: "The museum features a variety of exhibits related to Nehru's life and India's post-independence history. The planetarium offers educational shows about space and astronomy.",
    image: "https://th.bing.com/th/id/OIP.aqSTNSPKtLBGdJjem0odxgHaE8?w=273&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Teen Murti Bhavan, New Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "30 rs.",
    ratings: "4.4/5"
  },
  {
    title: "Tropical Villa in Bali",
    description: "Indulge in luxury at this tropical villa in Bali, featuring private pools, lush gardens, and Balinese hospitality.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Secluded Cabin in Norway",
    description: "Find peace in this secluded cabin in Norway, nestled among fjords and forests with stunning natural views.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Bergen",
    country: "Norway",
    title: "The Asiatic Society",
    description: "The Asiatic Society Museum in Kolkata is renowned for its extensive collection of manuscripts, rare books, and historical artifacts related to Asia.",
    history: "Established in 1784 by Sir William Jones, the museum is one of the oldest institutions dedicated to the study of Asian culture and history.",
    relatedinfo: "The museum's collection includes over 100,000 manuscripts, including several ancient and rare texts.",
    image: "https://th.bing.com/th/id/OIP.4Z6-5ok-sMuA1A-Ynrg9OwHaE8?w=263&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "1 Park Street, Kolkata, West Bengal 700016, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "Free",
    ratings: "4.4/5"
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the heart of the desert at this oasis in Dubai, featuring modern amenities and Arabian hospitality.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Dubai",
    country: "United Arab Emirates",
    title: "Rajasthan State Museum",
    description: "Located in Jaipur, the Rajasthan State Museum features an impressive collection of artifacts showcasing the rich history and culture of Rajasthan.",
    history: "Founded in 1949, the museum is situated in the Albert Hall, a historic building that was established to house the museum's collection.",
    relatedinfo: "The museum’s exhibits include paintings, sculptures, textiles, and artifacts from various periods of Rajasthan's history.",
    image: "https://th.bing.com/th/id/OIP.a08divBdYpPzrNS032xT0wAAAA?w=272&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Albert Hall Museum, Ram Niwas Garden, Jaipur, Rajasthan 302004, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "50 rs.",
    ratings: "4.3/5"
  },
  {
    title: "Rainforest Retreat in Costa Rica",
    description: "Immerse yourself in nature at this rainforest retreat in Costa Rica, surrounded by exotic wildlife and lush greenery.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 2300,
    location: "Monteverde",
    country: "Costa Rica",
    title: "Delhi Museum",
    description: "The Delhi Museum, also known as the Delhi Archaeological Museum, displays a variety of artifacts from ancient Indian civilizations.",
    history: "Established in 1960, the museum focuses on the history and archaeology of Delhi and the surrounding regions.",
    relatedinfo: "Exhibits include ancient coins, pottery, and sculptures from the Mauryan, Gupta, and Mughal periods.",
    image: "https://th.bing.com/th/id/OIP.7e--SjkimGdd2OqMD4a_KAHaE7?w=275&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Central Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.2/5"
  },
  {
    title: "Historic Mansion in Spain",
    description: "Stay in this historic mansion in Spain, offering elegant interiors and a glimpse into the country's rich heritage.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 2700,
    location: "Seville",
    country: "Spain",
    title: "The National Gallery of Modern Art",
    description: "The National Gallery of Modern Art in New Delhi houses an extensive collection of modern and contemporary Indian art.",
    history: "Founded in 1954, the gallery is located in the former residence of the Maharaja of Jaipur.",
    relatedinfo: "The gallery features works by prominent Indian artists from the 19th century to the present day, including paintings, sculptures, and installations.",
    image: "https://th.bing.com/th/id/OIP.JTcfovSzUG9mdwOuJfS_ngHaE8?w=244&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Rajpath, Central Secretariat, New Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.5/5"
  },
  {
    title: "Luxury Apartment in Tokyo",
    description: "Experience the vibrant city life in Tokyo from this luxury apartment, featuring modern design and top-notch amenities.",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Tokyo",
    country: "Japan",
    title: "Nehru Museum & Planetarium",
    description: "Located in New Delhi, the Nehru Museum & Planetarium, also known as the Nehru Memorial Museum and Library, is dedicated to India's first Prime Minister, Jawaharlal Nehru.",
    history: "Inaugurated in 1964, the museum was established to honor Nehru's contributions to Indian politics and education.",
    relatedinfo: "The museum features a variety of exhibits related to Nehru's life and India's post-independence history. The planetarium offers educational shows about space and astronomy.",
    image: "https://th.bing.com/th/id/OIP.kCwt1dXAWm2Vblv0PPy1gwHaE7?w=266&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    location: "Teen Murti Bhavan, New Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "30 rs.",
    ratings: "4.4/5"
  },
  {
    title: "Cozy Cottage in Canada",
    description: "Enjoy a serene escape in this cozy cottage in Canada, surrounded by nature and perfect for a relaxing getaway.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Banff",
    country: "Canada",
    title: "The Asiatic Society",
    description: "The Asiatic Society Museum in Kolkata is renowned for its extensive collection of manuscripts, rare books, and historical artifacts related to Asia.",
    history: "Established in 1784 by Sir William Jones, the museum is one of the oldest institutions dedicated to the study of Asian culture and history.",
    relatedinfo: "The museum's collection includes over 100,000 manuscripts, including several ancient and rare texts.",
    image: "https://th.bing.com/th?id=OIP.zmB1GZNpLzd1pRMyoniH_wHaHR&w=252&h=247&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    location: "1 Park Street, Kolkata, West Bengal 700016, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "Free",
    ratings: "4.4/5"
  },
  {
    title: "Charming Bungalow in Thailand",
    description: "Stay in this charming bungalow in Thailand, offering a unique blend of traditional Thai architecture and modern comforts.",
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    price: 1900,
    location: "Chiang Mai",
    country: "Thailand",
    title: "Rajasthan State Museum",
    description: "Located in Jaipur, the Rajasthan State Museum features an impressive collection of artifacts showcasing the rich history and culture of Rajasthan.",
    history: "Founded in 1949, the museum is situated in the Albert Hall, a historic building that was established to house the museum's collection.",
    relatedinfo: "The museum’s exhibits include paintings, sculptures, textiles, and artifacts from various periods of Rajasthan's history.",
    image: "https://th.bing.com/th?id=OIP.IiW4tAugqKdV6pH6AfjjhQHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    location: "Albert Hall Museum, Ram Niwas Garden, Jaipur, Rajasthan 302004, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "50 rs.",
    ratings: "4.3/5"
  },
  {
    title: "Mountain Cabin in Austria",
    description: "Experience the Austrian Alps from this cozy mountain cabin, perfect for skiing and outdoor adventures.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 2100,
    location: "Innsbruck",
    country: "Austria",
    title: "Delhi Museum",
    description: "The Delhi Museum, also known as the Delhi Archaeological Museum, displays a variety of artifacts from ancient Indian civilizations.",
    history: "Established in 1960, the museum focuses on the history and archaeology of Delhi and the surrounding regions.",
    relatedinfo: "Exhibits include ancient coins, pottery, and sculptures from the Mauryan, Gupta, and Mughal periods.",
    image: "https://th.bing.com/th?id=OIP.MqjujFDWINEUI96y9Io2rQHaE8&w=306&h=204&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    location: "Central Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.2/5"
  },
  {
    title: "Seaside Villa in Portugal",
    description: "Relax in this seaside villa in Portugal, offering stunning views of the Atlantic Ocean and luxurious amenities.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 2600,
    location: "Algarve",
    country: "Portugal",
    title: "The National Gallery of Modern Art",
    description: "The National Gallery of Modern Art in New Delhi houses an extensive collection of modern and contemporary Indian art.",
    history: "Founded in 1954, the gallery is located in the former residence of the Maharaja of Jaipur.",
    relatedinfo: "The gallery features works by prominent Indian artists from the 19th century to the present day, including paintings, sculptures, and installations.",
    image: "https://th.bing.com/th?id=OIP.EyRGRE0XxAb0jfmGItm2UwAAAA&w=280&h=222&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    location: "Rajpath, Central Secretariat, New Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "20 rs.",
    ratings: "4.5/5"
  },
  {
    title: "Rustic Lodge in Montana",
    description: "Experience the rugged beauty of Montana in this rustic lodge, surrounded by mountains and wide-open spaces.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Bozeman",
    country: "United States",
  },
  {
    title: "Eco Lodge in South Africa",
    description: "Stay at this eco-friendly lodge in South Africa, offering luxury accommodations and stunning views of the African savannah.",
    image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&w=800&q=60",
    price: 3100,
    location: "Kruger National Park",
    country: "South Africa",
  },
  {
    title: "Urban Jungle Hostel",
    description: "A vibrant hostel in the heart of the city, perfect for backpackers and digital nomads.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=60",
    price: 700,
    location: "Bangkok",
    country: "Thailand"
  },
  {
    title: "Desert Dome Experience",
    description: "Sleep under the stars in a luxury desert dome with all modern amenities.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Jaisalmer",
    country: "India"
  },
  {
    title: "City Center Hotel Room",
    description: "A modern hotel room in the heart of the city, perfect for business and leisure travelers.",
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Delhi",
    country: "India"
  },
  {
    title: "Boutique Hostel Bed",
    description: "A cozy hostel bed in a stylish boutique hostel, great for solo travelers.",
    image: "https://images.unsplash.com/photo-1519974719765-e6559eac2575?auto=format&fit=crop&w=800&q=60",
    price: 600,
    location: "Barcelona",
    country: "Spain"
  },
  {
    title: "Luxury Resort Suite",
    description: "Spacious suite in a luxury resort with pool and sea view.",
    image: "https://images.unsplash.com/photo-1501117716987-c8e1ecb210fa?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Goa",
    country: "India"
    title: "Nehru Museum & Planetarium",
    description: "Located in New Delhi, the Nehru Museum & Planetarium, also known as the Nehru Memorial Museum and Library, is dedicated to India's first Prime Minister, Jawaharlal Nehru.",
    history: "Inaugurated in 1964, the museum was established to honor Nehru's contributions to Indian politics and education.",
    relatedinfo: "The museum features a variety of exhibits related to Nehru's life and India's post-independence history. The planetarium offers educational shows about space and astronomy.",
    image: "https://th.bing.com/th?id=OIP.H44hqLjLzVh01o9_EpaNdAHaE6&w=306&h=203&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    location: "Teen Murti Bhavan, New Delhi, Delhi 110001, India",
    openingtime: "10:00 AM",
    closingtime: "5:00 PM",
    ticketfees: "30 rs.",
    ratings: "4.4/5"
  }
];


module.exports = { data: sampleListings };